<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-Konverter Hitungan Kurs_SourceNumber</name>
   <tag></tag>
   <elementGuidId>a2424c43-84cc-4d57-a10b-07c9d6a4540a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SourceNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SourceNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e7b9a34-0011-4599-97a6-7031ae625280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txNumber numberPicker</value>
      <webElementGuid>37bc0f00-2dda-42d8-83b4-045d6cb9c830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SourceNumber</value>
      <webElementGuid>e7225e79-be6b-45ff-9627-751372a84e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SourceNumber</value>
      <webElementGuid>69b6e268-76bf-4c87-9203-2c6b6ecd4aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>34d2d2ce-cefa-4c7d-90bb-c84e19a56deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e3233eaf-6800-42a6-b032-3adbfaede969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SourceNumber&quot;)</value>
      <webElementGuid>26899766-b9ea-47c8-b8f5-c538d7ab2d6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SourceNumber']</value>
      <webElementGuid>01bb3269-b056-4dc0-be58-18ca82d6ac92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>7edd5b22-fea2-4b79-83be-e39d8a71591c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SourceNumber' and @name = 'SourceNumber' and @type = 'text']</value>
      <webElementGuid>1a818ee4-2385-4240-b195-c7135d1c362c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
