<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_USDJPYGBPAUDHKDSGDEURIDRMYRSARCNY</name>
   <tag></tag>
   <elementGuidId>86f41006-52a7-4205-a36b-6434d27bbd7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='CurrencyCode'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>efd8ce41-2356-4396-bda0-cd90297f796a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cbCurrencyTo</value>
      <webElementGuid>0dfafabe-e6b8-4bb0-942c-39561ab93a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CurrencyCode</value>
      <webElementGuid>367e54ce-21b1-4b00-abfe-97b1162b1f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CurrencyCode</value>
      <webElementGuid>a97815a9-97bf-42e0-a054-0acb0608601d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>USD
JPY
GBP
AUD
HKD
SGD
EUR
IDR
MYR
SAR
CNY
</value>
      <webElementGuid>d55b4fe5-702b-445d-be52-f285495d35a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;btn-wrapper&quot;]/div[@class=&quot;btn-content&quot;]/section[@class=&quot;section-area mb-40&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-7&quot;]/div[@class=&quot;converter-box converter-box__wrapper&quot;]/div[@class=&quot;converter-box__content&quot;]/form[@class=&quot;form-converter&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-3&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;select-wrapper select-kurs1&quot;]/select[@id=&quot;CurrencyCode&quot;]</value>
      <webElementGuid>d3e42d98-d97b-4f4b-bbb6-b00a12a49324</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='CurrencyCode'])[2]</value>
      <webElementGuid>bf045d52-1699-4f15-b9ac-611b91501940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaksi'])[1]/following::select[2]</value>
      <webElementGuid>c06c425a-0ba2-4235-b254-12b3f9ddeeb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-Konverter Hitungan Kurs'])[2]/following::select[3]</value>
      <webElementGuid>4a35bf78-b1ed-4b41-8885-91577e41778b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD'])[7]/preceding::select[1]</value>
      <webElementGuid>4e08471c-3b99-484b-a732-aa10ca62314f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JPY'])[6]/preceding::select[1]</value>
      <webElementGuid>0c512dcf-7b7a-4d7e-aa54-647389216e38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/select</value>
      <webElementGuid>d22db9f9-03c8-4364-8d9e-1a6dbc139887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'CurrencyCode' and @name = 'CurrencyCode' and (text() = 'USD
JPY
GBP
AUD
HKD
SGD
EUR
IDR
MYR
SAR
CNY
' or . = 'USD
JPY
GBP
AUD
HKD
SGD
EUR
IDR
MYR
SAR
CNY
')]</value>
      <webElementGuid>d969721a-6bb1-4f23-b0ab-de4cf67971e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
